#Gym Management System Settings - © 2026
#Sun May 31 23:51:27 EEST 2026
admin-config.properties=test
autoBackup=true
backupPath=./backups
currency=\u062C\u0646\u064A\u0647 \u0645\u0635\u0631\u064A (\u062C.\u0645)
expiryDays=7
gymName=Digital Store
logging.level.com.gym=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.root=WARN
lowStockUnits=5
spring.application.name=GYM
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.password=
spring.datasource.url=jdbc\:h2\:./data/gymdb
spring.datasource.username=sa
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
